### ISSUE TITLE
How should the usage of names be handled on the website?

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#109]
Kristijan mentioned in #105 that there's need for discussion.

My view: the members of each group should decide individually who they want to let in. For that, we need the feature to approve members before they can enter the group.

There's no way to easily find out if the user entered his real name. Also, the tolerance level is different: is "Nick" allowed for someone called "Nicholas"... is "Bodhi" forbidden if your passport says "David" but most of your friends don't even know it?

**Comment by Sliverriver** [comment]
but who approves? 
There are some names that are obviously false. Having the questions for "first name" "last name" i rarely see any wrong names entering a community group in foodsharing. It is easily made out. 
If it is just asked for a nickname or screenname then a nickname will be given and no real name and an indirect "oh who wants can give their real name in screen name" doesn't work because it is not clear enough. 
There are some obvious names who are fake - just have a look at a facebook friendlist - there you find all variations. 

I really got used to and appreciate that on foodsharing.de there are real/clear names. It just puts a level of trust and reminder that behind every profile is a real person, and it is much easier to connect people during meetings etc. As it is not only a pure online forum but also connects people in the offline world.

**Comment by PaulFree14** [comment]
Elke from foodsharing in Berlin (as I know) told me about some issues with "real name". 
On the passport there's a different name standing, but no one is calling her by that name,  but Elke. 
In the foodsharing form she was somehow "forced" to enter her "real-name" and for her it's not to nice. Cause she doen't like to get called by the "real-name". 

My aproach is that everyone should have the right to deside on the same they like to be called. 

But what  I see also usefull is that people don't use encrypted names. 

- people should be encouraged to choose a name they wish to be called. 
(for the most it is the "real-name" for some not) 
(maybe also firts and secound name? ....for the reason that it's confusing with multible same first names)

**Comment by nicksellen** [comment]
As this is meant to be a general purpose tool, not specific to one community, I think it's something the community should decide on, not the software.

I would suggest to keep the simplest possible model for now (e.g. one field called "display name" or similar), and then as actual communities start using it and find concrete use cases, they can suggest having more flexibility at that point.

Some communities might need the full legal passport name for a one aspect of the site, but that might be something that stays hidden from public, and is just for making the agreement (like where you might have a seperate billing address to a delivery address on a website).

It's simply not possible to make one simple policy that covers all people and all use cases.

**Comment by tiltec** [comment]
Agree with Nick. Therefore: require and show `display_name`.
Offer a field `legal name` (or first/last name as long as we are focused on Europe) for ID checks

**Comment by djahnie** [comment]
Also completely agree with Nick, it's for the communities to decide.
Tilmann's proposal sounds great as it offers the possibility to enter the legal name as well and even points out that it is indeed the legal name and not just some official-sounding nickname...

**Comment by tiltec** [comment]
This issue is solved, see Nick's comment.
