### ISSUE TITLE
Comment field for pickup dates

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#158]
Show where the food will be distributed. Should be optional.
One field per user per pickup, or just one field per pickup?

**Comment by tiltec** [comment]
Could also be solved with the same simple text field as in #156

**Comment by djahnie** [comment]
Yay to free text fields!
Let the users decide on how to use them and just add nicely figured out test groups, where we show examples of how it could be handled (for the less creative ones...^^).

**Comment by tiltec** [comment]
This needs backend implementation before starting with the frontend: https://github.com/yunity/foodsaving-backend/issues/253

**Comment by brnsolikyl** [comment]
Feedback from Gbg: It would be awesome if you could prioritize this feature. It would be really useful for us in order to communicate simple things, like the meeting point before a pick-up, which sometimes varies depending on the people doing it.

Moreover, in the future it would be very very useful to have a discussion forum/wall for each store (due to whatever issues may come up in the cooperation, so that all foodsavers are aware of them and can participate). I have only found a mention to it on the roadmap though, as an idea.

**Comment by tiltec** [comment]
Thanks! This is already in the highest priority (Release 3), so waiting for Devs to pick it up!

**Comment by tiltec** [comment]
I will go for a text field per pickup that everyone can edit. It will be possible to set default content for a series.

Would it also make sense to attach a simple communication feature to a pickup? @nicksellen 
I would go for the simple text field that everyone can edit, but I would prefer per-user messages, e.g. a chat-like interface or a wall.

**Comment by nicksellen** [comment]
@tiltec given the conversation/chat proposal is not quite agreed yet, or implemented I would suggest to continue with the comment as planned, but could revisit it in the future. In theory though, yes sounds like a good use case for a reusable communication channel that can be attached to different objects, and presented in different forms as needed.
