### ISSUE TITLE
Show historic pickup dates

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-frontend#177]
Pickup dates should only contain the buttons ```LEAVE``` / ```JOIN``` when they aren't in the past.

**Comment by tiltec** [comment]
I would not display past pickups at all in the standard view. Or would it be helpful to have the pickups of the past 24 hours visible?

**Comment by alangecker** [comment]
i would differentiate between the group overview and storeDetails
**group:** at least the current ongoing pickups should be visible, let's say for an hour?
**storeDetail:** much less pickups, so a longer time acceptable (1 week?)

Use Cases:
- Where can i help? _-> group_
- I wanna see whats happening right now _-> group_
- Who was this person again I picked up with last week? (e.g. problems, invite,...) _-> store_

**Comment by tiltec** [comment]
makes sense, we could split between historic and upcoming pickups in the store view!

**Comment by tiltec** [comment]
I think historic pickups are not required for testing.

**Comment by brnsolikyl** [comment]
Hey y'all! Glad to be here for the first time, thx for the invitation @djahnie!

One of the first priorities for foodsavers in Gothenburg would be for pick-ups to remain visible, as a motivation for people to start adopting and using this tool. Right now do not have a lot of stores and foodsavers, so it's been easier to manage it with other tools (sms, phone calls, e-mails), but we have seen an increase of pick-ups and of new people interested in rescuing food. The history function would be crucial then as a motivational factor for people to participate (besides notifications). If new foodsavers log in and see nothing, because pickups were already assigned or done, they'll just think nothing is happening.

**Comment by djahnie** [comment]
Thanks for the feedback @brnsolikyl! I guess motivation is a pretty good reason to display past pickups...

I think the store view is the right place for this. Either made visible with a specific filter setting (which is still quite hidden IMHO) or in another column on the right from the upcoming pickups (which could be _too_ prominent and probably doesn't work on small phone screens, hm...). They should display the foodsavers who took part as well as the date. but since this is info that is stored in the database anyways it should only be a frontend change, right? Ah yes, and the button to join/leave should be hidden of course... ;)

**Comment by alangecker** [comment]
i'm about to implement a history tab for groups & stores - combining the logs and historic pick-ups in this style: 
![screenshot_2017-02-17_15-55-12](https://cloud.githubusercontent.com/assets/10246027/23070163/7082276a-f52a-11e6-9204-90acc4638488.png)

## Questions:
- should we do that in that way?
- should we either
  * A: combine both data sources (log & pick-ups) in the frontend
  * B: save past pick-up dates also in the log
Problems with A occur when a store gets deleted, but it requires much less effort

**Comment by tiltec** [comment]
@alangecker nice idea! It could be useful that way..
It also gives me an idea how to better handle historic pickup dates in the backend. Currently they don't change when they happen, but if we add them to an log table and remove them from the pickups table, some things could be simplified.
