### ISSUE TITLE
Creating a new store: set weeks_in_advance to 4 (backend default)

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#376]
Currently it shows an empty slider. Should show the backend default of 4 weeks.

Related task: should we somehow load server defaults via API instead of hardcoding them in the frontend?

**Comment by b-lawrence** [comment]
Hi @tiltec, 

I noticed something while _creating_ a new `store`. 

The new newly added `store` isn't added to the `stores` pane on the left when a new store is created. This would mean that the `stores` model data, which is most likely an array isn't updated with the newly created `store` object on successful creation. It does show up there when you refresh the page, though. Is this an expected behavior?

**Comment by tiltec** [comment]
This should be fixed in `master` (https://dev.foodsaving.world) and the map update will be fixed with #403
It's basically a dataflow problem, I wrote some lengthy thoughts about this in #361 
I'm happy about better ideas :)

**Comment by b-lawrence** [comment]
Noted @tiltec!

**Comment by tiltec** [comment]
Maybe we should just hide the slider on creating a store? It's not so important and the default can be edited later on.
