### ISSUE TITLE
Notification page should provide "Home" page link/access

### ISSUE THREAD

**Issue by karunaguru** [yunity/foodsaving-frontend#488]
when we click notifications page ( https://foodsaving.world/#!/notifications ), the resulting page will not have access to home page.  Its good to have icon with the link to home page as normal practice.
![homepage-link-missing](https://cloud.githubusercontent.com/assets/25746404/25858568/0f8219ce-34aa-11e7-917e-9bcf2aa51a6a.JPG)

**Comment by tiltec** [comment]
You can access the group home page by clicking on "Foodsharing Rotterdam".

There's no link to the landing page however. Why is that necessary?

**Comment by tiltec** [comment]
We could add the "house" button from the "logged out" topbar to the "logged in" view. Thoughts?

**Comment by dkreimer** [comment]
Hi, I'm a newcomer to the open source community and this seems like something I can tackle to dip my toes! Can I work on this?

**Comment by djahnie** [comment]
This touches the general navigation planning for the page, which is actually not yet really figured out... 😅 
What exactly would you do @dkreimer? Insert the house button for the user to go back to the group view page (which actually clicking on the name of the group already permits) or would it link to the landing page, so that the user can access the blog, the world map and the team page again?
