### ISSUE TITLE
Remove base service, create validation service

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#49]
base superclass is collecting random code, better separate it into individual services.

**Comment by Xbaal** [comment]
What exactly do we want to validate?
I mean, what should be validated client-side and what do we just leave up to the server?

I would just start with not validating on client-side, because it is easier to code.
On the other hand it would be nice, if any wrong use of a function would directly throw a meaningful error.

**Comment by tiltec** [comment]
You're right, validation seems not necessary at this point. We should rely on the server to return the status, even if it takes a bit more time.
Validation could be an optimization to speed up the frontend in future.

**Comment by Sneezoo** [comment]
Validation is important, you should do this on both sides client and server. But that's an issue we could work on later. But at least I want to make an issue for that so that we won't forget (but overlook) it.
This looks like a good validation library which would make our code cleaner: https://github.com/hapijs/joi
