### ISSUE TITLE
Initiation period for users a.k.a introductory pickups

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#99]
Foodsharing initiatives in Nantes, Warszawa and generally in Germany (foodsharing.de) use the method of introductory pickups to get new foodsavers familiar with the special circumstances of stores.

For now, I would suggest that only approved members get access to the group (by restricting the join capabilities). Therefore, all members of the group will be able to pick up at all stores.

In the future, it takes a lot of work to manage the people who haven't completed the initiation yet (especially if it is per store), so I suggest the following feature idea: **initiation**.
A new group member can see the pickups of the groups, and join them together with another person (who is already initiated). After one _guided pickup_, the new member can also pickup food alone at this store. For each store, another initiation is required. You can never lose the initiation status.

What do you think?

**Comment by tiltec** [comment]
I would definitely wait for direct feedback from active foodsavers before starting to implement this.

**Comment by D0nPiano** [comment]
I think it makes sense to approve a new member somehow. I'm definitely for implementing it.

**Comment by PaulFree14** [comment]
How about this: 

- only aproved members get access to the pick up group
- as a new user you can register at the webpage and will resieve some basic informations 
- you have then also the possibility of click on "become a foodsaver" from there it show an ivitation to --.the "welcome party" (or whatever) 
(the welcome party is an event to introduce new commers into the foodsaving community, incl. workshops and disco spoup) 
that the party is fun and that the newcommers make enough connections to the community the idea would be to have a counter. (7-11) ....if it's combined with a bigger event (30-100 ppl) 

- Once enough ppl are interested (so it supports people to ask their friends) everyone resieves a message incl. the invitation to the event. 

- On the event you get told a password (a funny one, educational, political or whatever) which then can be used to have access to the foodsaver group. 
Once you've typed it in you have access and you never need to repeat it. 
The passwort is created randomnly out of a list of a couple of funny words. 

- On this welcome party thing they get anything told they need to know, incl. an invitation for the first pick up. 
- New users have a sign on their profil to be regongizable for others that they are new.
- they can't do pickups alone

**Comment by butze7** [comment]
@tiltec I like your idea with the initiation very good. Especially that the new user can already click on a slot & pick up food (but just if another experienced foodsaver is picking up together with the new user)
I like paul's idea of a "invitation event" that is happening once 10 new users have signed up. Although I have a feeling that can be already kind of imposed. It would be nice as an additional tool, that already gives you then templates of "how to do a invitation event", "how to do disco soup"
And I like the "new user" sign

**Comment by djahnie** [comment]
Initiation to every single store makes sense in my opinion. Also to reduce the trial pick-ups to just one, but then one in each store. Like it!

@PaulFree14's suggestion sounds nice for a group to perform in a certain location, but to implement in the general software seems too much to me, 1. because it describes elaborate features which are not needed right now and 2. because we don't know the circumstances of all the different groups and therefore cannot say if they'd be up for holding events like the ones you mentioned and 3. what if only 9 people sing up and the 10th is missing for weeks, will no event take place at all and will the people get notified?
Still, I like the idea of a one-time password as well, and I like the newbie badge! And like I said, newbie events in general are a great idea (!) I just wouldn't make them part of the foodsaving tool.

**Comment by PaulFree14** [comment]
"A new group member can see the pickups of the groups, and join them together with another person (who is already initiated). After one guided pickup, the new member can also pickup food alone at this store." 
...I just have the feeling that "only" this promotes a bit the idea of mainly being a consumer. (that's something I would really like to avoid) 
It also initates that foodsaving probably creates a community where members aren't well connected. 

- I agree that the tool should be for the first release be simple

Having a counter and incl. the passwort function seems to be reduced on mainly all what it needs to funtion. 
The basics of the counter is already existing, writen by eric for glocall yunity.

**Comment by PaulFree14** [comment]
> what if only 9 people sing up and the 10th is missing for weeks
Missing for weeks would mean they have not much interest in engaging to other people. But I guess more the opposide is happening. 
first scenario
If people want to build it up, want to save food, want to build up a network, why should they be to lazy to tell others about this initative. 

secound
If people are saving food, intereted in building a network, interested in social connection, why shouldn't they be interested in joining/creating welcomming events? 

> will the people get notified?
yes

> because we don't know the circumstances of all the different groups and therefore cannot say if they'd be up for holding events like the ones you mentioned
True.  Do you mean events in gerneral or the once I mentioned. Cause it can be basicly just any event. Just so that new people can be introduced to a network. 
...but yes maybe there are groups they don't like to have events, but are they then groups or more like individuals  getting free food from the supermarkets...

> 1. because it describes elaborate features which are not needed right now and
yes. So maybe just counter and passwort function for the first. 
I'm not a dev. but yes it seems to be a bit more work, but not to much of a different. Comparing with the result I would say it's worth to do. 
...but I'm not a dev. ^^

**Comment by tiltec** [comment]
In #363 there was a request for having the roles _students_ and _instructor_. Students are members that are not experienced, while instructors have the knowledge to introduce newcomers to pickup up food at a store.

From what I understood:

Are all non-students automatically instructors? - I would say yes.
How do you get a student? - by joining the group
How to get an instructor? - by getting marked as experienced by another instructor
Who will be instructor first? - the group creator.

What can students do/what can instructors do? - I think that is closely related to #356 
Should we treat instructors as group admins / trusted users? - Could make sense to simplify implementation and to enable hierarchical equality between instructors.

**Comment by djahnie** [comment]
If all non-student are automatically instructors, what do we need the experience mark for?
If all non-student are automatically instructors, can non-students turn off their instructor status? (I think they should definitely be able to, cause there's nothing worse than a demotivated teacher...)

If an experience mark is needed to become an instructor, I think it makes sense to make them admins as well.
If an experience mark is needed to become an instructor, should we/anybody define criteria what it means to be experienced?

**Comment by nicksellen** [comment]
I'm closing this as we've moved it into a clearer issue - https://github.com/yunity/foodsaving-frontend/issues/546
